# Run the full experiment suite: every method script, every figure, and a
# regenerated results/RESULTS.md.
#
# Runs entirely offline on the committed CSVs under data/ (falling back to
# the identical base-R built-ins if they are absent). No external packages.
#
# Usage:
#   Rscript scripts/run_all.R

file_arg <- sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE)[1])
root <- tryCatch(dirname(dirname(normalizePath(file_arg))), error = function(e) getwd())
if (!dir.exists(file.path(root, "R"))) root <- getwd()

# Each experiment script defines a report_* function and is a no-op when
# sourced (the standalone entry point is guarded by sys.nframe() == 0).
source(file.path(root, "scripts", "01_hypothesis_tests.R"))
source(file.path(root, "scripts", "02_anova.R"))
source(file.path(root, "scripts", "03_regression.R"))
source(file.path(root, "scripts", "04_pca_factor.R"))
source(file.path(root, "scripts", "05_association_rules.R"))

# Draw the hero figure: a 2x2 diagnostics panel pairing the PCA biplot and
# scree curve with the linear-model residual diagnostics.
make_diagnostics_panel <- function(datasets, out_dir) {
  fit <- linear_regression(datasets$mtcars)$fit
  pca <- run_pca(datasets$arrests)
  png(file.path(out_dir, "diagnostics_panel.png"), width = 1300, height = 1200)
  op <- par(mfrow = c(2, 2), mar = c(4.5, 4.5, 3.5, 1.5), cex = 1.1)
  biplot(stats::prcomp(datasets$arrests, scale. = TRUE),
         main = "PCA biplot of USArrests", col = c("grey45", "steelblue"),
         cex = c(0.7, 1.0))
  plot_scree(pca$var_explained, main = "USArrests variance explained")
  plot(fit, which = 1, pch = 19, col = "grey40")
  plot(fit, which = 2, pch = 19, col = "grey40")
  par(op)
  invisible(dev.off())
}

datasets <- load_datasets(file.path(root, "data"))
transactions <- load_transactions(file.path(root, "data"))
out_dir <- ensure_dir(file.path(root, "results"))

md <- c(
  "# Results",
  "",
  "Generated by `Rscript scripts/run_all.R` on the committed sample data",
  "under `data/` (exact copies of base-R datasets plus a seed-1 transaction",
  "set, see `data/README.md`). Base R only, no external packages, no network.",
  "Association-rule transactions use `set.seed(1)`, so every number below is",
  "reproducible bit for bit.",
  "",
  sprintf("R version used for this run: %s.", getRversion()),
  ""
)

section("Hypothesis tests")
md <- c(md, report_hypothesis_tests(datasets, out_dir))

section("Analysis of variance")
md <- c(md, report_anova(datasets, out_dir))

section("Regression")
md <- c(md, report_regression(datasets, out_dir))

section("Dimensionality reduction")
md <- c(md, report_pca_factor(datasets, out_dir))

section("Association rules")
md <- c(md, report_association(transactions, out_dir))

make_diagnostics_panel(datasets, out_dir)
md <- c(md, "## Diagnostics panel", "",
        "The combined hero figure, `results/diagnostics_panel.png`, pairs the",
        "PCA biplot and scree curve with the linear-model residual diagnostics.",
        "")

writeLines(md, file.path(out_dir, "RESULTS.md"))
cat("\nWrote", length(list.files(out_dir, pattern = "[.]png$")),
    "figures and RESULTS.md to", out_dir, "\n")
